<?php 

$config['fancyupload_active'] = '';
$config['fancyupload_max_upload'] = '0';
$config['fancyupload_type'] = 'photoqueue';
$config['fancyupload_folder'] = '/Volumes/Data/Sites/ionize-connect/files/pictures/';
$config['fancyupload_file_prefix'] = '';
$config['fancyupload_send_alert'] = '';
$config['fancyupload_send_confirmation'] = '';
$config['fancyupload_email'] = '';
$config['fancyupload_group'] = '';


/* End of file config.php */
/* Auto generated by FancyUpload Administration on : 2010.09.07 23:52:14 */
/* Location: modules/Fancyupload/config/config.php */
