<?php 

// Medias base folder. Used by all external plugin wich needs.
$config['files_path'] = 'files/';


/* End of file medias.php */
/* Auto generated by Themes Administration on : 2010.09.06 19:19:15 */
/* Location: application/config/medias.php */
