<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'fancyupload' => 'Fancyupload',
	'search' => 'Search'
	);

$aliases = array(

	);



/* End of file modules.php */
/* Auto generated by Themes Administration on : 2010.09.08 09:18:51 */
/* Location: application//config/modules.php */
